// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/Message.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_personal     MessageType = 0
	MessageType_muc          MessageType = 1
	MessageType_ack          MessageType = 2
	MessageType_notification MessageType = 3
)

var MessageType_name = map[int32]string{
	0: "personal",
	1: "muc",
	2: "ack",
	3: "notification",
}
var MessageType_value = map[string]int32{
	"personal":     0,
	"muc":          1,
	"ack":          2,
	"notification": 3,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Message_e3d5cfe6bd4e310d, []int{0}
}

type Header struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=message.MessageType" json:"type,omitempty"`
	From                 string      `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string      `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_e3d5cfe6bd4e310d, []int{0}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (dst *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(dst, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_personal
}

func (m *Header) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Header) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type Body struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ExtContent           string   `protobuf:"bytes,2,opt,name=extContent,proto3" json:"extContent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()    {}
func (*Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_e3d5cfe6bd4e310d, []int{1}
}
func (m *Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body.Unmarshal(m, b)
}
func (m *Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body.Marshal(b, m, deterministic)
}
func (dst *Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body.Merge(dst, src)
}
func (m *Body) XXX_Size() int {
	return xxx_messageInfo_Body.Size(m)
}
func (m *Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Body proto.InternalMessageInfo

func (m *Body) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Body) GetExtContent() string {
	if m != nil {
		return m.ExtContent
	}
	return ""
}

type Message struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *Body    `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_Message_e3d5cfe6bd4e310d, []int{2}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Message) GetBody() *Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "message.Header")
	proto.RegisterType((*Body)(nil), "message.Body")
	proto.RegisterType((*Message)(nil), "message.Message")
	proto.RegisterEnum("message.MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("message/Message.proto", fileDescriptor_Message_e3d5cfe6bd4e310d) }

var fileDescriptor_Message_e3d5cfe6bd4e310d = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4f, 0x4f, 0x84, 0x30,
	0x10, 0xc5, 0xe5, 0x4f, 0xc0, 0x1d, 0xd6, 0x95, 0x4c, 0x34, 0xe1, 0x64, 0x56, 0x2e, 0x12, 0x0f,
	0x98, 0xe0, 0x07, 0xd0, 0xe8, 0xc5, 0x8b, 0x97, 0x46, 0xbd, 0x77, 0xa1, 0xab, 0x44, 0xe9, 0x10,
	0x18, 0x13, 0xf9, 0xf6, 0x66, 0x87, 0xee, 0x66, 0x4f, 0x9d, 0xbe, 0xf7, 0xfa, 0xfa, 0x6b, 0xe1,
	0xb2, 0x33, 0xe3, 0xa8, 0x3f, 0xcd, 0xdd, 0xeb, 0xbc, 0x96, 0xfd, 0x40, 0x4c, 0x18, 0x3b, 0x39,
	0xff, 0x80, 0xe8, 0xc5, 0xe8, 0xc6, 0x0c, 0x58, 0x40, 0xc8, 0x53, 0x6f, 0x32, 0x6f, 0xed, 0x15,
	0xab, 0xea, 0xa2, 0x74, 0x89, 0xd2, 0x1d, 0x7c, 0x9b, 0x7a, 0xa3, 0x24, 0x81, 0x08, 0xe1, 0x76,
	0xa0, 0x2e, 0xf3, 0xd7, 0x5e, 0xb1, 0x50, 0x32, 0xe3, 0x0a, 0x7c, 0xa6, 0x2c, 0x10, 0xc5, 0x67,
	0xca, 0x1f, 0x21, 0x7c, 0xa2, 0x66, 0xc2, 0x0c, 0xe2, 0x9a, 0x2c, 0x1b, 0xcb, 0x52, 0xbc, 0x50,
	0xfb, 0x2d, 0x5e, 0x01, 0x98, 0x3f, 0x7e, 0x76, 0xe6, 0xdc, 0x75, 0xa4, 0xe4, 0xef, 0x10, 0xbb,
	0xab, 0xf1, 0x06, 0xa2, 0x2f, 0x81, 0x94, 0x8e, 0xa4, 0x3a, 0x3f, 0xc0, 0xcd, 0xec, 0xca, 0xd9,
	0x78, 0x0d, 0xe1, 0x86, 0x9a, 0x49, 0xda, 0x92, 0xea, 0xec, 0x10, 0xdb, 0xa1, 0x28, 0xb1, 0x6e,
	0x1f, 0x20, 0x39, 0x7a, 0x11, 0x2e, 0xe1, 0xb4, 0x37, 0xc3, 0x48, 0x56, 0xff, 0xa4, 0x27, 0x18,
	0x43, 0xd0, 0xfd, 0xd6, 0xa9, 0xb7, 0x1b, 0x74, 0xfd, 0x9d, 0xfa, 0x98, 0xc2, 0xd2, 0x12, 0xb7,
	0xdb, 0xb6, 0xd6, 0xdc, 0x92, 0x4d, 0x83, 0x4d, 0x24, 0x3f, 0x78, 0xff, 0x1f, 0x00, 0x00, 0xff,
	0xff, 0x18, 0x26, 0xf2, 0xef, 0x5a, 0x01, 0x00, 0x00,
}
